apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mvc-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mvc-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mvc-app-service
                port: 
                  number: 80


